### ISSUE TITLE
Upgrade to latest piston-graphics

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/glium_graphics#111]
The draw state has been simplified, which requires a different mapping to Glium draw state.

Convert from sRGB to linear color space.

**Comment by gaborigloi** [comment]
I had a go at this (but not the sRGB conversion): https://github.com/gaborigloi/glium_graphics/tree/latest-graphics, this compiles with the latest piston2d-graphics.
To upgrade, most of the time I just followed what the opengl_backend does.
I also updated piston-texture to the latest version.

I noticed two things:
* The definition of alpha blending in Piston is different from alpha blending in glium for the alpha channel.
  piston2d-graphics says `new_dest_alpha = src_alpha + dest_alpha`, but what glium does is
  `new_dest_alpha = src_alpha * src_alpha + dest_alpha * (1 - src_alpha)`.
  Therefore I could not use `glium::Blend::alpha_blending()`, had to construct the Blend manually.
* For `graphics::draw_state::Blend::Invert`, I used this blending:
 
 `new_dest_color = (ref_color - dst_color) * src_color`,

 but the equation in the rustdoc of `Invert` is different, it says

 `new_dest_color = ref_color - src_color`.

Also, I'm not sure what formatting to use, I'm still new to Rust. Should I just run rustfmt to format the code, or is the current formatting ok?

**Comment by gaborigloi** [comment]
Opened a pull request: https://github.com/PistonDevelopers/glium_graphics/pull/112

**Comment by gaborigloi** [comment]
The minor version probably needs to be incremented, I'm not sure about that.

**Comment by bvssvni** [comment]
I think piston-graphics used the alpha equation from Gfx, but after doing some research it seems neither Glium or Gfx uses the correct one. Opened https://github.com/PistonDevelopers/graphics/issues/1042

**Comment by bvssvni** [comment]
For now, we could use `new_dest_alpha = src_alpha + dest_alpha`.
