### ISSUE TITLE
Add support for clamp to border (waiting for Glium 0.26.0)

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/glium_graphics#188]

**Comment by wizzwizz4** [comment]
Can this be done now? Glium 0.26.0 has been released, and (as far as I can tell) it works fine as a drop-in replacement for this crate.

Disclaimer: I have an ulterior motive for wanting this done; the dependency on exactly Glium 0.25.0 has meant I've had to fork glium_graphics for the sole purpose of changing the Cargo.toml file.
