### ISSUE TITLE
image_test example flickers on OSX

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/glium_graphics#44]
`rustc 1.0.0-nightly (07560d233 2015-04-20) (built 2015-04-19)`

OSX 10.9.5

**Comment by tomaka** [comment]
Hmm, someone mentionned something similar on IRC with glium and OS/X. I have no idea where it could come from though.

**Comment by tomaka** [comment]
Nevermind, I just asked and it was something totally different.

**Comment by bvssvni** [comment]
It seems this bug is caused by a double swapping of buffers. Changing into `window.events().swap_buffers(false)` fixed the problem.
