### ISSUE TITLE
Don't put texture in an Arc

### ISSUE THREAD

**Issue by aepsil0n** [PistonDevelopers/glium_graphics#6]
Currently the Glium textures are wrapped in an `Arc`. I did this to conform to the `BackEnd` trait, but I think there should be a better way to do this. Possibly the `BackEnd` trait leaks the state machine logic through its interface by having methods such as `color`, `enable_texture` and `disable_texture`. This is not necessary for Glium, as it does not expose such state.

**Comment by bvssvni** [comment]
I'll do this now since the new texture design might take some time to land.
