### ISSUE TITLE
Implement `texture::Rgba8Texture` for `DrawTexture`

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/glium_graphics#73]
- [x] Add dependency on piston-texture
- [x] Reexport `texture::*` at top level
- [ ] Implement `Rgba8Texture` for `DrawTexture`

Can copy code from https://github.com/PistonDevelopers/gfx_texture/blob/master/src/lib.rs#L115-L161

**Comment by bvssvni** [comment]
@tomaka recommended to use `TextureAny`.

**Comment by tomaka** [comment]
Using a `TextureAny` is blocked on https://github.com/tomaka/glium/issues/1035

**Comment by bvssvni** [comment]
We could implement `Rgba8Texture` for `DrawTexture` for now, and change to `TextureAny` later when Glium gets updated.
