### ISSUE TITLE
Examples are Broken, attempts to fix lead to dependency hell

### ISSUE THREAD

**Issue by cybergeek94** [PistonDevelopers/glium_graphics#75]
The Piston Ecosystem has gotten a lot messier since I last checked in. What should be a simple dependency version bump and refactor leads to a downward spiral into madness as every crate in the dependency chain tries to compile a different version of its ancestors.

I just want to bootstrap a game using the latest version of everything, not to have to hunt down or try to figure out a list of crate versions that don't break each other. 

I don't know what's going on here but it's a huge barrier to (re)entry.

**Comment by bvssvni** [comment]
Make sure to use piston = "0.4.1". I thought Cargo was watching my back but it turned out the dependencies worked differently when publishing, causing a conflict in downstream for 0.4.0.

**Comment by bvssvni** [comment]
Wait, I see glium_graphics is not yet updated. Working on it.

**Comment by bvssvni** [comment]
Done! Should be working now.
